spring:
  application:
    name: query-dsl-tutorial
  # h2 ??
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  #jpa
  jpa:
    database: h2
    generate-ddl: true
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        highlight_sql: true
    hibernate:
      ddl-auto: create
